export const LANGUAGES = {
  en: {
    appName: 'Numero',
    selectLanguage: 'Select Language',
    dashboard: 'Number Challenges',
    numberTap: 'Number Tap',
    mathSprint: 'Math Sprint', 
    memoryNumbers: 'Memory Numbers',
    patternMatch: 'Pattern Match',
    time: 'Time',
    best: 'Best',
    tap: 'Tap',
    start: 'Start!',
    tapping: 'Tapping...',
    newRecord: '🎉 New Record!',
    completed: '✅ Completed!',
    timeText: 'Time',
    bestText: 'Best',
    description: 'Tap numbers 1-25 in order as fast as you can!',
    back: 'Back',
    score: 'Score',
    level: 'Level',
    correct: 'Correct!',
    wrong: 'Wrong!',
    remember: 'Remember the sequence!',
    yourTurn: 'Your turn!',
    patternComplete: 'Pattern Complete!',
    solve: 'Solve:',
    answer: 'Answer',
    next: 'Next'
  },
  es: {
    appName: 'Numero',
    selectLanguage: 'Seleccionar Idioma',
    dashboard: 'Desafíos de Números',
    numberTap: 'Toque de Números',
    mathSprint: 'Carrera Matemática',
    memoryNumbers: 'Números de Memoria',
    patternMatch: 'Coincidencia de Patrones',
    time: 'Tiempo',
    best: 'Mejor',
    tap: 'Toca',
    start: '¡Comenzar!',
    tapping: 'Tocando...',
    newRecord: '🎉 Nuevo Record!',
    completed: '✅ Completado!',
    timeText: 'Tiempo',
    bestText: 'Mejor',
    description: '¡Toca los números 1-25 en orden lo más rápido que puedas!',
    back: 'Atrás',
    score: 'Puntuación',
    level: 'Nivel',
    correct: '¡Correcto!',
    wrong: '¡Incorrecto!',
    remember: '¡Recuerda la secuencia!',
    yourTurn: '¡Tu turno!',
    patternComplete: '¡Patrón Completado!',
    solve: 'Resuelve:',
    answer: 'Respuesta',
    next: 'Siguiente'
  },
  fr: {
    appName: 'Numéro',
    selectLanguage: 'Choisir la Langue',
    dashboard: 'Défis Numériques',
    numberTap: 'Tap Numérique',
    mathSprint: 'Course Mathématique',
    memoryNumbers: 'Mémoire des Nombres',
    patternMatch: 'Modèle à Suivre',
    time: 'Temps',
    best: 'Meilleur',
    tap: 'Appuyez',
    start: 'Commencer!',
    tapping: 'En cours...',
    newRecord: '🎉 Nouveau Record!',
    completed: '✅ Terminé!',
    timeText: 'Temps',
    bestText: 'Meilleur',
    description: 'Appuyez sur les nombres 1-25 dans l\'ordre le plus vite possible!',
    back: 'Retour',
    score: 'Score',
    level: 'Niveau',
    correct: 'Correct!',
    wrong: 'Faux!',
    remember: 'Souviens-toi de la séquence!',
    yourTurn: 'À ton tour!',
    patternComplete: 'Modèle Terminé!',
    solve: 'Résoudre:',
    answer: 'Réponse',
    next: 'Suivant'
  },
  de: {
    appName: 'Nummer',
    selectLanguage: 'Sprache Auswählen',
    dashboard: 'Zahlen-Herausforderungen',
    numberTap: 'Zahlen Tippen',
    mathSprint: 'Mathe-Sprint',
    memoryNumbers: 'Zahlen Gedächtnis',
    patternMatch: 'Muster Erkennen',
    time: 'Zeit',
    best: 'Beste',
    tap: 'Tippen',
    start: 'Starten!',
    tapping: 'Tippen...',
    newRecord: '🎉 Neuer Rekord!',
    completed: '✅ Abgeschlossen!',
    timeText: 'Zeit',
    bestText: 'Beste',
    description: 'Tippe die Zahlen 1-25 in der richtigen Reihenfolge so schnell wie möglich!',
    back: 'Zurück',
    score: 'Punktzahl',
    level: 'Level',
    correct: 'Richtig!',
    wrong: 'Falsch!',
    remember: 'Merke dir die Sequenz!',
    yourTurn: 'Du bist dran!',
    patternComplete: 'Muster Vollständig!',
    solve: 'Löse:',
    answer: 'Antwort',
    next: 'Weiter'
  },
  it: {
    appName: 'Numero',
    selectLanguage: 'Seleziona Lingua',
    dashboard: 'Sfide Numeriche',
    numberTap: 'Tocco Numerico',
    mathSprint: 'Corsa Matematica',
    memoryNumbers: 'Memoria Numerica',
    patternMatch: 'Corrispondenza Modelli',
    time: 'Tempo',
    best: 'Migliore',
    tap: 'Tocca',
    start: 'Iniziare!',
    tapping: 'Toccando...',
    newRecord: '🎉 Nuovo Record!',
    completed: '✅ Completato!',
    timeText: 'Tempo',
    bestText: 'Migliore',
    description: 'Tocca i numeri 1-25 in ordine il più velocemente possibile!',
    back: 'Indietro',
    score: 'Punteggio',
    level: 'Livello',
    correct: 'Corretto!',
    wrong: 'Sbagliato!',
    remember: 'Ricorda la sequenza!',
    yourTurn: 'Il tuo turno!',
    patternComplete: 'Modello Completato!',
    solve: 'Risolvi:',
    answer: 'Risposta',
    next: 'Avanti'
  },
  pt: {
    appName: 'Número',
    selectLanguage: 'Selecionar Idioma',
    dashboard: 'Desafios Numéricos',
    numberTap: 'Toque Numérico',
    mathSprint: 'Corrida Matemática',
    memoryNumbers: 'Memória Numérica',
    patternMatch: 'Combinação de Padrões',
    time: 'Tempo',
    best: 'Melhor',
    tap: 'Toque',
    start: 'Começar!',
    tapping: 'Tocando...',
    newRecord: '🎉 Novo Recorde!',
    completed: '✅ Concluído!',
    timeText: 'Tempo',
    bestText: 'Melhor',
    description: 'Toque nos números 1-25 em ordem o mais rápido que puder!',
    back: 'Voltar',
    score: 'Pontuação',
    level: 'Nível',
    correct: 'Correto!',
    wrong: 'Errado!',
    remember: 'Lembre-se da sequência!',
    yourTurn: 'Sua vez!',
    patternComplete: 'Padrão Concluído!',
    solve: 'Resolva:',
    answer: 'Resposta',
    next: 'Próximo'
  },
  ja: {
    appName: '数字',
    selectLanguage: '言語を選択',
    dashboard: '数字チャレンジ',
    numberTap: '数字タップ',
    mathSprint: '計算スプリント',
    memoryNumbers: '数字記憶',
    patternMatch: 'パターンマッチ',
    time: '時間',
    best: 'ベスト',
    tap: 'タップ',
    start: 'スタート!',
    tapping: 'タップ中...',
    newRecord: '🎉 新記録!',
    completed: '✅ 完了!',
    timeText: '時間',
    bestText: 'ベスト',
    description: '1から25までの数字を順番に素早くタップしてください！',
    back: '戻る',
    score: 'スコア',
    level: 'レベル',
    correct: '正解!',
    wrong: '不正解!',
    remember: 'シーケンスを覚えて！',
    yourTurn: 'あなたの番！',
    patternComplete: 'パターン完了！',
    solve: '解決：',
    answer: '答え',
    next: '次へ'
  },
  ko: {
    appName: '숫자',
    selectLanguage: '언어 선택',
    dashboard: '숫자 도전',
    numberTap: '숫자 탭',
    mathSprint: '수학 스프린트',
    memoryNumbers: '숫자 기억',
    patternMatch: '패턴 매치',
    time: '시간',
    best: '최고',
    tap: '탭',
    start: '시작!',
    tapping: '탭하는 중...',
    newRecord: '🎉 신기록!',
    completed: '✅ 완료!',
    timeText: '시간',
    bestText: '최고',
    description: '1부터 25까지의 숫자를 순서대로 최대한 빠르게 탭하세요!',
    back: '뒤로',
    score: '점수',
    level: '레벨',
    correct: '정답!',
    wrong: '오답!',
    remember: '순서를 기억하세요!',
    yourTurn: '당신 차례!',
    patternComplete: '패턴 완성!',
    solve: '풀기:',
    answer: '답변',
    next: '다음'
  },
  zh: {
    appName: '数字',
    selectLanguage: '选择语言',
    dashboard: '数字挑战',
    numberTap: '数字点击',
    mathSprint: '数学冲刺',
    memoryNumbers: '数字记忆',
    patternMatch: '模式匹配',
    time: '时间',
    best: '最佳',
    tap: '点击',
    start: '开始!',
    tapping: '点击中...',
    newRecord: '🎉 新纪录!',
    completed: '✅ 完成!',
    timeText: '时间',
    bestText: '最佳',
    description: '尽可能快地按顺序点击数字1-25！',
    back: '返回',
    score: '分数',
    level: '等级',
    correct: '正确!',
    wrong: '错误!',
    remember: '记住顺序！',
    yourTurn: '轮到你了！',
    patternComplete: '模式完成！',
    solve: '解决：',
    answer: '答案',
    next: '下一个'
  },
  ru: {
    appName: 'Номер',
    selectLanguage: 'Выбрать Язык',
    dashboard: 'Числовые Испытания',
    numberTap: 'Числовой Тап',
    mathSprint: 'Математический Спринт',
    memoryNumbers: 'Память Чисел',
    patternMatch: 'Совпадение Паттернов',
    time: 'Время',
    best: 'Лучший',
    tap: 'Нажми',
    start: 'Начать!',
    tapping: 'Нажимаем...',
    newRecord: '🎉 Новый Рекорд!',
    completed: '✅ Завершено!',
    timeText: 'Время',
    bestText: 'Лучший',
    description: 'Нажимайте числа 1-25 по порядку как можно быстрее!',
    back: 'Назад',
    score: 'Счет',
    level: 'Уровень',
    correct: 'Правильно!',
    wrong: 'Неправильно!',
    remember: 'Запомни последовательность!',
    yourTurn: 'Твоя очередь!',
    patternComplete: 'Паттерн Завершен!',
    solve: 'Реши:',
    answer: 'Ответ',
    next: 'Далее'
  },
  ar: {
    appName: 'رقم',
    selectLanguage: 'اختر اللغة',
    dashboard: 'تحديات الأرقام',
    numberTap: 'نقرة الرقم',
    mathSprint: 'سباق الرياضيات',
    memoryNumbers: 'ذاكرة الأرقام',
    patternMatch: 'مطابقة النمط',
    time: 'الوقت',
    best: 'الأفضل',
    tap: 'انقر',
    start: 'ابدأ!',
    tapping: 'جاري النقر...',
    newRecord: '🎉 رقم قياسي جديد!',
    completed: '✅ اكتمل!',
    timeText: 'الوقت',
    bestText: 'الأفضل',
    description: 'انقر على الأرقام من 1 إلى 25 بالترتيب بأسرع ما يمكن!',
    back: 'رجوع',
    score: 'النقاط',
    level: 'المستوى',
    correct: 'صحيح!',
    wrong: 'خطأ!',
    remember: 'تذكر التسلسل!',
    yourTurn: 'دورك!',
    patternComplete: 'اكتمل النمط!',
    solve: 'حل:',
    answer: 'الإجابة',
    next: 'التالي'
  },
  hi: {
    appName: 'नंबर',
    selectLanguage: 'भाषा चुनें',
    dashboard: 'संख्या चुनौतियाँ',
    numberTap: 'संख्या टैप',
    mathSprint: 'गणित स्प्रिंट',
    memoryNumbers: 'संख्या स्मृति',
    patternMatch: 'पैटर्न मिलान',
    time: 'समय',
    best: 'सर्वश्रेष्ठ',
    tap: 'टैप',
    start: 'शुरू!',
    tapping: 'टैप कर रहे...',
    newRecord: '🎉 नया रिकॉर्ड!',
    completed: '✅ पूरा!',
    timeText: 'समय',
    bestText: 'सर्वश्रेष्ठ',
    description: '1-25 तक की संख्याओं को क्रम से जितनी तेजी से टैप कर सकते हैं!',
    back: 'वापस',
    score: 'स्कोर',
    level: 'स्तर',
    correct: 'सही!',
    wrong: 'गलत!',
    remember: 'अनुक्रम याद रखें!',
    yourTurn: 'आपकी बारी!',
    patternComplete: 'पैटर्न पूरा!',
    solve: 'हल करें:',
    answer: 'उत्तर',
    next: 'अगला'
  }
};

export type LanguageCode = keyof typeof LANGUAGES;